#pragma once
#include "pid.h"
#include "brew_fsm.h"

extern float currentTemp;
extern PIDController pid;
extern unsigned long brewMs;
extern unsigned long preinfusionMs;
extern unsigned long pauseMs;
extern float getBrewSetpoint();
extern float getSteamSetpoint();
extern bool emergencyStop;
extern String emergencyReason;

inline String renderHomePage() {
  String html =
    "<!doctype html><html><head>"
    "<meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    "<title>Lilit Anita Espresso</title>"
    "<style>"
    ":root{--bg:#f6f1e6;--card:#ffffff;--ink:#2a241e;--muted:#6f655c;--accent:#c46a2f;--accent2:#2f6f5c;}"
    "body{margin:0;font-family:'Trebuchet MS',Verdana,sans-serif;background:radial-gradient(1200px 800px at 20% -10%,#fff6e3 0%,#f2e7d4 35%,#e9dcc6 100%);color:var(--ink);}"
    ".wrap{max-width:520px;margin:0 auto;padding:20px;}"
    ".hero{background:linear-gradient(135deg,#fff 0%,#f7efe2 100%);border:1px solid #ead9c3;border-radius:18px;padding:18px 18px 14px;box-shadow:0 10px 30px rgba(45,32,20,.08);}"
    "h1{margin:0 0 6px;font-size:26px;letter-spacing:.5px;}"
    ".temp{font-size:34px;font-weight:700;margin:6px 0 8px;}"
    ".sub{color:var(--muted);font-size:13px;}"
    ".grid{display:grid;grid-template-columns:1fr;gap:12px;margin-top:16px;}"
    ".card{background:var(--card);border:1px solid #ead9c3;border-radius:16px;padding:14px;}"
    "label{display:block;font-size:12px;color:var(--muted);margin-bottom:6px;text-transform:uppercase;letter-spacing:.6px;}"
    "input{width:90%;padding:12px 12px;border:1px solid #e0d1be;border-radius:12px;font-size:16px;background:#fffaf2;}"
    "input[type=range]{width:100%;height:28px;padding:0;accent-color:var(--accent);}"
    ".brew-slider-wrap{display:flex;align-items:center;gap:10px;margin-top:8px;}"
    ".brew-slider-wrap input[type=number]{width:4em;flex-shrink:0;}"
    ".brew-slider-wrap input[type=range]{flex:1;}"
    ".row{display:grid;grid-template-columns:1fr 1fr;gap:10px;}"
    ".actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px;}"
    "button{width:100%;padding:12px 14px;border-radius:14px;border:0;font-size:16px;font-weight:700;color:#fff;}"
    ".save{background:var(--accent);}"
    ".start{background:var(--accent2);}"
    ".stop{background:#8d2e2e;}"
    ".note{font-size:12px;color:var(--muted);margin-top:8px;}"
    ".emergency{background:#8d2e2e;color:#fff;padding:15px;border-radius:14px;margin-bottom:16px;font-weight:700;text-align:center;border:2px solid #ff0000;}"
    "#heater_indicator{font-size:20px;line-height:1;}.heater-on{color:var(--accent);}.heater-off{color:var(--muted);opacity:0.6;}"
    ".emergency-badge{display:inline-block;background:#8d2e2e;color:#fff;padding:6px 12px;border-radius:10px;font-size:14px;font-weight:700;margin-top:8px;}"
    "</style></head><body>"
    "<div class='wrap'>"
    "<div id='emergency_banner' class='emergency' style='display:" + String(emergencyStop ? "block" : "none") + "'>"
    "ВНИМАНИЕ: АВАРИЙНАЯ ОСТАНОВКА<br><small id='emergency_text'>" + emergencyReason + "</small>"
    "</div>"
    "<div class='hero'>"
    "<h1>Lilit Espresso</h1>"
    "<div style='display:flex;align-items:center;gap:10px;flex-wrap:wrap;'>"
    "<span id='temp' class='temp'>" + String(currentTemp, 1) + " C</span>"
    "<span id='heater_indicator' class='heater-off' title='Нагрев'>●</span>"
    "</div>"
    "<div id='setpoint' class='sub'>Заданная температура " + String(pid.getSetpoint(),1) + " C</div>"
    "<div id='mode' class='sub'>Режим: пролив</div>"
    "<div id='emergency_badge' class='emergency-badge' style='display:" + String(emergencyStop ? "inline-block" : "none") + "' title='Причина аварии'>Аварийный режим</div>"
    "</div>"
    "<div class='grid'>"
    "<div class='card'>"
    "<label>Состояние</label>"
    "<div id='state' style='font-size:18px;font-weight:700;'>Ожидание</div>"
    "<div style='margin-top:8px;font-size:13px;color:var(--muted);'>"
    "Этап: <span id='phase'>—</span>"
    " · <span id='remaining_label'>Осталось</span>: <span id='remaining'>—</span>"
    "</div>"
    "<div style='margin-top:12px;'>"
    "<div style='height:10px;background:#efe3d2;border-radius:10px;overflow:hidden;'>"
    "<div id='progress' style='height:10px;width:0%;background:linear-gradient(90deg,#c46a2f,#2f6f5c);'></div>"
    "</div>"
    "</div>"
    "</div>"
    "<div class='card'>"
    "<label>Нагрев</label>"
    "<div class='actions'>"
    "<form id='heater_off_form' action='/heater_off' method='POST'><button type='submit' class='stop'>Выключить</button></form>"
    "<form id='heater_on_form' action='/heater_on' method='POST' style='display:none'><button type='submit' class='start'>Включить</button></form>"
    "</div>"
    "<div class='note'>Выключить: уставка 20 °C. Включить: восстановить заданную температуру.</div>"
    "</div>"
    "<div class='card'>"
    "<label>Управление</label>"
    "<div class='actions'>"
    "<form action='/start' method='POST'><button class='start'>Старт</button></form>"
    "<form action='/stop' method='POST'><button class='stop'>Стоп</button></form>"
    "</div>"
    "</div>"
    "<form class='card' action='/set' method='POST'>"
    "<label>Температура (C)</label>"
    "<input name='t' inputmode='decimal' value='" + String(getBrewSetpoint(),1) + "'>"
    "<div class='note'>Пар: " + String(getSteamSetpoint(),1) + " C</div>"
    "<div class='row' style='margin-top:12px;'>"
    "<div><label>Предсмачивание (с)</label><input id='pre_sec' name='pre' inputmode='numeric' value='" + String(preinfusionMs/1000) + "'></div>"
    "<div><label>Пауза (с)</label><input id='pause_sec' name='pause' inputmode='numeric' value='" + String(pauseMs/1000) + "'></div>"
    "</div>"
    "<div style='margin-top:12px;'><label>Экстракция (с)</label>"
    "<div class='brew-slider-wrap'><input id='brew_sec' name='brew' type='number' min='5' max='90' value='" + String(brewMs/1000) + "'><input id='brew_slider' type='range' min='5' max='90' step='1' value='" + String(brewMs/1000) + "'></div></div>"
    "<div style='margin-top:14px;'><button class='save' type='submit'>Сохранить</button></div>"
    "<div class='note' id='times_note'>Поле — задать и сохранить. Ползунок — менять время динамически во время пролива.</div>"
    "</form>"
    "<div class='card'>"
    "<label>Режим</label>"
    "<div class='actions' style='margin-top:10px;'>"
    "<form action='/mode_brew' method='POST'><button class='start'>Пролив</button></form>"
    "<form action='/mode_steam' method='POST'><button class='save'>Пар</button></form>"
    "</div>"
    "</div>"
    "<div class='card' style='display:none'>"
    "<label>Отладка</label>"
    "<div class='actions' style='margin-top:10px;'>"
    "<form action='/autotune_start' method='POST'><button class='save'>Autotune</button></form>"
    "<form action='/autotune_stop' method='POST'><button class='stop'>Stop Autotune</button></form>"
    "</div>"
    "</div>"
    "</div>"
    "</div>"
    "<script>"
    "const stateMap={idle:'Ожидание',preinfusion:'Предсмачивание',pause:'Пауза',brew:'Экстракция'};"
    "const phaseMap={idle:'—',preinfusion:'Предсмачивание',pause:'Пауза',brew:'Экстракция'};"
    "function fmtMs(ms){const s=Math.max(0,Math.floor(ms/1000));const m=Math.floor(s/60);const r=s%60;return m+':' + (r<10?'0':'')+r;}"
    "async function tick(){"
    "try{const r=await fetch('/api/status',{cache:'no-store'});const d=await r.json();"
    "if(d.emergency){"
    "document.getElementById('emergency_banner').style.display='block';"
    "document.getElementById('emergency_text').textContent=d.emergency_reason;"
    "var eb=document.getElementById('emergency_badge');eb.style.display='inline-block';eb.textContent='Аварийный режим';eb.title=d.emergency_reason||'';"
    "}else{"
    "document.getElementById('emergency_banner').style.display='none';"
    "document.getElementById('emergency_badge').style.display='none';"
    "}"
    "document.getElementById('temp').textContent=d.temp.toFixed(1)+' C';"
    "var sb=!!d.heater_standby;"
    "document.getElementById('heater_off_form').style.display=sb?'none':'block';"
    "document.getElementById('heater_on_form').style.display=sb?'block':'none';"
    "var hi=document.getElementById('heater_indicator');"
    "hi.textContent='●';hi.className=d.heater?'heater-on':'heater-off';hi.title=d.heater?'Нагрев вкл':'Нагрев выкл';"
    "document.getElementById('setpoint').textContent='Заданная температура '+d.setpoint.toFixed(1)+' C';"
    "document.getElementById('mode').textContent='Режим: '+(d.mode==='steam'?'пар':'пролив');"
    "const isManual=!!d.manual;"
    "document.getElementById('state').textContent=isManual?'Ручной пролив':(stateMap[d.state]||d.state);"
    "document.getElementById('phase').textContent=isManual?'Ручной':(phaseMap[d.state]||'—');"
    "const showElapsed=!isManual && d.state==='brew';"
    "document.getElementById('remaining_label').textContent=isManual?'—':(showElapsed?'Прошло':'Осталось');"
    "document.getElementById('remaining').textContent=isManual?'—':fmtMs(showElapsed?d.elapsed_ms:d.remaining_ms);"
    "const total=isManual?0:(d.phase_ms||0);const pct=total?Math.min(100,Math.round((d.elapsed_ms/total)*100)):0;"
    "document.getElementById('progress').style.width=pct+'%';"
    "var brewSl=document.getElementById('brew_slider');var brewF=document.getElementById('brew_sec');"
    "if(brewSl&&brewF&&d.state==='brew'&&total>0){var sec=Math.round(total/1000);sec=Math.max(5,Math.min(90,sec));brewSl.value=sec;brewF.value=sec;}"
    "}catch(e){}"
    "}"
    "var timesDebounce=null;"
    "function sendTimes(){"
    "var pre=document.getElementById('pre_sec');var pause=document.getElementById('pause_sec');var brew=document.getElementById('brew_sec');"
    "if(!pre||!pause||!brew)return;"
    "var fd=new FormData();fd.append('pre',pre.value||'0');fd.append('pause',pause.value||'0');fd.append('brew',brew.value||'0');"
    "fetch('/api/set_times',{method:'POST',body:fd}).catch(function(){});"
    "}"
    "function scheduleSendTimes(){if(timesDebounce)clearTimeout(timesDebounce);timesDebounce=setTimeout(sendTimes,400);}"
    "(function(){"
    "var pre=document.getElementById('pre_sec');var pause=document.getElementById('pause_sec');var brew=document.getElementById('brew_sec');var brewSl=document.getElementById('brew_slider');"
    "if(pre){pre.addEventListener('change',sendTimes);pre.addEventListener('input',scheduleSendTimes);}"
    "if(pause){pause.addEventListener('change',sendTimes);pause.addEventListener('input',scheduleSendTimes);}"
    "if(brew){brew.addEventListener('change',function(){if(brewSl){brewSl.value=brew.value;}sendTimes();});brew.addEventListener('input',function(){if(brewSl){brewSl.value=brew.value;}scheduleSendTimes();});}"
    "if(brewSl){brewSl.addEventListener('input',function(){var v=brewSl.value;if(brew){brew.value=v;}sendTimes();});brewSl.addEventListener('change',function(){var v=brewSl.value;if(brew){brew.value=v;}sendTimes();});}"
    "})();"
    "setInterval(tick,1000);tick();"
    "</script>"
    "</body></html>";

  return html;
}
