#pragma once
#include "pid.h"
#include "brew_fsm.h"

extern float currentTemp;
extern PIDController pid;
extern unsigned long brewMs;
extern unsigned long preinfusionMs;
extern unsigned long pauseMs;
extern float getBrewSetpoint();
extern float getSteamSetpoint();

inline String renderHomePage() {
  String html =
    "<!doctype html><html><head>"
    "<meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    "<title>Lilit Anita Espresso</title>"
    "<style>"
    ":root{--bg:#f6f1e6;--card:#ffffff;--ink:#2a241e;--muted:#6f655c;--accent:#c46a2f;--accent2:#2f6f5c;}"
    "body{margin:0;font-family:'Trebuchet MS',Verdana,sans-serif;background:radial-gradient(1200px 800px at 20% -10%,#fff6e3 0%,#f2e7d4 35%,#e9dcc6 100%);color:var(--ink);}"
    ".wrap{max-width:520px;margin:0 auto;padding:20px;}"
    ".hero{background:linear-gradient(135deg,#fff 0%,#f7efe2 100%);border:1px solid #ead9c3;border-radius:18px;padding:18px 18px 14px;box-shadow:0 10px 30px rgba(45,32,20,.08);}"
    "h1{margin:0 0 6px;font-size:26px;letter-spacing:.5px;}"
    ".temp{font-size:34px;font-weight:700;margin:6px 0 8px;}"
    ".sub{color:var(--muted);font-size:13px;}"
    ".grid{display:grid;grid-template-columns:1fr;gap:12px;margin-top:16px;}"
    ".card{background:var(--card);border:1px solid #ead9c3;border-radius:16px;padding:14px;}"
    "label{display:block;font-size:12px;color:var(--muted);margin-bottom:6px;text-transform:uppercase;letter-spacing:.6px;}"
    "input{width:90%;padding:12px 12px;border:1px solid #e0d1be;border-radius:12px;font-size:16px;background:#fffaf2;}"
    ".row{display:grid;grid-template-columns:1fr 1fr;gap:10px;}"
    ".actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px;}"
    "button{width:100%;padding:12px 14px;border-radius:14px;border:0;font-size:16px;font-weight:700;color:#fff;}"
    ".save{background:var(--accent);}"
    ".start{background:var(--accent2);}"
    ".stop{background:#8d2e2e;}"
    ".note{font-size:12px;color:var(--muted);margin-top:8px;}"
    "</style></head><body>"
    "<div class='wrap'>"
    "<div class='hero'>"
    "<h1>Lilit Espresso</h1>"
    "<div id='temp' class='temp'>" + String(currentTemp,1) + " C</div>"
    "<div id='setpoint' class='sub'>Заданная температура " + String(pid.getSetpoint(),1) + " C</div>"
    "<div id='mode' class='sub'>Режим: пролив</div>"
    "</div>"
    "<div class='grid'>"
    "<div class='card'>"
    "<label>Состояние</label>"
    "<div id='state' style='font-size:18px;font-weight:700;'>Ожидание</div>"
    "<div style='margin-top:8px;font-size:13px;color:var(--muted);'>"
    "Этап: <span id='phase'>—</span>"
    " · <span id='remaining_label'>Осталось</span>: <span id='remaining'>—</span>"
    "</div>"
    "<div style='margin-top:12px;'>"
    "<div style='height:10px;background:#efe3d2;border-radius:10px;overflow:hidden;'>"
    "<div id='progress' style='height:10px;width:0%;background:linear-gradient(90deg,#c46a2f,#2f6f5c);'></div>"
    "</div>"
    "</div>"
    "</div>"
    "<form class='card' action='/set' method='POST'>"
    "<label>Температура (C)</label>"
    "<input name='t' inputmode='decimal' value='" + String(getBrewSetpoint(),1) + "'>"
    "<div class='note'>Пар: " + String(getSteamSetpoint(),1) + " C</div>"
    "<div class='row' style='margin-top:12px;'>"
    "<div><label>Предсмачивание (с)</label><input name='pre' inputmode='numeric' value='" + String(preinfusionMs/1000) + "'></div>"
    "<div><label>Пауза (с)</label><input name='pause' inputmode='numeric' value='" + String(pauseMs/1000) + "'></div>"
    "</div>"
    "<div style='margin-top:12px;'><label>Экстракция (с)</label><input name='brew' inputmode='numeric' value='" + String(brewMs/1000) + "'></div>"
    "<div style='margin-top:14px;'><button class='save' type='submit'>Сохранить</button></div>"
    "<div class='note'>Изменения применяются сразу.</div>"
    "</form>"
    "<div class='card'>"
    "<label>Режим</label>"
    "<div class='actions' style='margin-top:10px;'>"
    "<form action='/mode_brew' method='POST'><button class='start'>Пролив</button></form>"
    "<form action='/mode_steam' method='POST'><button class='save'>Пар</button></form>"
    "</div>"
    "</div>"
    "<div class='card'>"
    "<label>Управление</label>"
    "<div class='actions'>"
    "<form action='/start' method='POST'><button class='start'>Старт</button></form>"
    "<form action='/stop' method='POST'><button class='stop'>Стоп</button></form>"
    "</div>"
    "</div>"
    "<div class='card'>"
    "<label>Отладка</label>"
    "<div class='actions' style='margin-top:10px;'>"
    "<form action='/autotune_start' method='POST'><button class='save'>Autotune</button></form>"
    "<form action='/autotune_stop' method='POST'><button class='stop'>Stop Autotune</button></form>"
    "</div>"
    "</div>"
    "</div>"
    "</div>"
    "<script>"
    "const stateMap={idle:'Ожидание',preinfusion:'Предсмачивание',pause:'Пауза',brew:'Экстракция'};"
    "const phaseMap={idle:'—',preinfusion:'Предсмачивание',pause:'Пауза',brew:'Экстракция'};"
    "function fmtMs(ms){const s=Math.max(0,Math.floor(ms/1000));const m=Math.floor(s/60);const r=s%60;return m+':' + (r<10?'0':'')+r;}"
    "async function tick(){"
    "try{const r=await fetch('/api/status');const d=await r.json();"
    "document.getElementById('temp').textContent=d.temp.toFixed(1)+' C';"
    "document.getElementById('setpoint').textContent='Заданная температура '+d.setpoint.toFixed(1)+' C';"
    "document.getElementById('mode').textContent='Режим: '+(d.mode==='steam'?'пар':'пролив');"
    "document.getElementById('state').textContent=stateMap[d.state]||d.state;"
    "document.getElementById('phase').textContent=phaseMap[d.state]||'—';"
    "const showElapsed=d.state==='brew';"
    "document.getElementById('remaining_label').textContent=showElapsed?'Прошло':'Осталось';"
    "document.getElementById('remaining').textContent=fmtMs(showElapsed?d.elapsed_ms:d.remaining_ms);"
    "const total=d.phase_ms||0;const pct=total?Math.min(100,Math.round((d.elapsed_ms/total)*100)):0;"
    "document.getElementById('progress').style.width=pct+'%';"
    "}catch(e){}"
    "}"
    "setInterval(tick,1000);tick();"
    "</script>"
    "</body></html>";

  return html;
}
